name: Build and deploy container app to Azure Web App - Monago

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run build

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://monago.azurecr.io/
          username: ${{ secrets.AzureAppService_ContainerUsername }}
          password: ${{ secrets.AzureAppService_ContainerPassword }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./
          tags: monago.azurecr.io/${{ secrets.AzureAppService_ContainerUsername }}/nginx:${{ steps.package-version.outputs.current-version }}
          file: ./Dockerfile
